### ISSUE TITLE
Layer count mismatch with backbone model

### ISSUE THREAD

**Issue by JacquelineKonkol** [ElenaRyumina/EMO-AffectNetModel#1]
When trying to load the weights for the backbone model with
```
from functions.get_models import load_weights_EE
EE_model = load_weights_EE('EmoAffectNet.h5')
```
I get the following error:

```
in load_weights_from_hdf5_group
    raise ValueError(
ValueError: Layer count mismatch when loading weights from file. Model expected 108 layers, found 107 saved layers
```

Do you have an idea what is wrong or what changes I can do to obtain a model that is working as intended?

Thanks!

**Comment by ElenaRyumina** [comment]
Thanks for your question. Please upload weights for backbone  model https://drive.google.com/drive/folders/1_AvhddwG9_-WuArYleWmE2AjTH5MbCkR?usp=sharing again.
The error was that there were no weights for the classifier. Now the weights are correct.

**Comment by JacquelineKonkol** [comment]
Works perfectly, thanks!

**Comment by soumyadbanik** [comment]
After uploading the weights of the backbone model, how can I merge it with my custom weights? Because the main error was raising only when we are trying to load custom resnet weights.

**Comment by ElenaRyumina** [comment]
Thanks for your question.
 
I don't understand at what stage (layer) you are trying to merge the weights of your custom model and the weights  of the backbone model. Could you describe the problem in detail or illustrate it? Perhaps you should check out the two architecture models. According to the topic of the letter, I see they have a different number of layers. I think you should remove some weights from both models so that they are compatible.
  
>Понедельник, 5 декабря 2022, 7:17 +03:00 от Soumyadeep Banik ***@***.***>:
> 
> 
>After uploading the weights of the backbone model, how can I merge it with my custom weights? Because the main error was raising only when we are trying to load custom resnet weights.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you modified the open/close state. Message ID:  <ElenaRyumina/EMO-AffectNetModel/issues/1/1336729363 @ github . com> 
 
 
╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾
Best regards, Elena Ryumina
╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾
E. Ryumina
Researcher of the Speech & Multimodal Interfaces Lab.,
St. Petersburg Institute for Informatics and Automation of 
the Russian Academy of Sciences (SPIIRAS Institute),
St. Petersburg Federal Research Center of
the Russian Academy of Sciences (SPC RAS)
SPIIRAS, 39, 14th line, St. Petersburg, 199178, Russia
╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾
Tel:  +7-911-818-91-65 ; 
Email:  ***@***.*** ,  ***@***.***
Web:  http://hci.nw.ru/en/employees/14
╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾
ResearcherID Web of Science
Scopus Author ID
Google Scholar ID
Semantic Scholar
╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾╼╾
